export default {
    pdf: ["application/pdf"],
    xls: [
        "application/excel",
        "application/x-excel",
        "application/x-msexcel",
        "application/vnd.ms-excel",
    ],
    img: [
        "image/png",
        "image/vnd.wap.wbmp",
        "image/tiff",
        "image/x-tiff",
        "image/jpeg",
        "image/pjpeg",
        "image/x-jps",
        "image/x-icon",
        "image/gif",
        "image/bmp",
        "image/x-windows-bmp",
    ],
    txt: [
        "text/plain",
    ],
    types: {
        "application/pdf": "pdf",
        "application/excel": "xls",
        "application/x-excel": "xls",
        "application/x-msexcel": "xls",
        "application/vnd.ms-excel": "xls",
        "image/png": "img",
        "image/vnd.wap.wbmp": "img",
        "image/tiff": "img",
        "image/x-tiff": "img",
        "image/jpeg": "img",
        "image/pjpeg": "img",
        "image/x-jps": "img",
        "image/x-icon": "img",
        "image/gif": "img",
        "image/bmp": "img",
        "image/x-windows-bmp": "img",
        "text/plain": "txt",
    },
};
